l_russian:
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nНекоторые культуры будут называть первый титул по имени династии (пример: Уршилаку)." #replacing Abbasids